sudo: required
services:
  - docker

before_install:
  - docker build -t laleh-shamkhali/docker-react-test -f Dockerfile.dev .

script:
  - docker run laleh-shamkhali/docker-react-test npm run test -- --coverage
